### ISSUE TITLE
Change the JobSeeker Dashboard metric PNG image

### ISSUE THREAD

**Issue by tayabsoomro** [vocationnations/wireframes#16]
**Actions**
Create an XY-plot for the JobSeeker dashboard as a PNG image.

- number matches BLUE (higher than both combined)
- number discards RED
- number applied GREEN (higher than discards)
- average dashed straight line which shows average number of job applied.

X-Y plot where x is weeks and y is the quantity

**Comment by MuatazBadr** [comment]
![image](https://user-images.githubusercontent.com/38388845/83978188-07225100-a8c3-11ea-8131-346b2799c332.png)

**Comment by MuatazBadr** [comment]
![image](https://user-images.githubusercontent.com/38388845/83978465-dc38fc80-a8c4-11ea-8d14-335d5e88e944.png)

**Comment by MuatazBadr** [comment]
![jobSeekerChart](https://user-images.githubusercontent.com/38388845/83978598-ef000100-a8c5-11ea-8c35-105ffc122e63.png)
