### ISSUE TITLE
Change in structure of 'Who Am I' and 'What Do I Want'

### ISSUE THREAD

**Issue by MarioTomberli** [vocationnations/wireframes#5]
**NOTE: THIS ISSUE REQUIRES YOU TO CREATE A NEW BRANCH AND MAKE PROGRESS ON THAT BRANCH. DO NOT TRY TO COMMIT TO MASTER, IT WILL LEAD TO A CATASTROPHE**

**Current State**
Currently when you look at [Employer Profile Builder](https://vocationnations.github.io/wireframes/components/EmployerDashboard/profilebuilder.html) "Who Are We" and "What Do I Want" tabs. _It sends a message that this information is for the company in general._ Whereas in reality, we want this information to be associated with each job that the employer creates.

**Specifics/Actions**
- Whenever an employer creates a job, we need to ask them "Who am I" questions that helps the employer reflects on what kind of company they are.
- Whenever an employer creates. a job, we need to ask them "What Do I Want" questions that helps employer reflect on what type of employee are they looking for FOR THAT PARTICULAR POSITION that they are CREATING THE JOB for.

Take it away!

**Comment by tayabsoomro** [comment]
This PR 1bfb9efb4f534af5fd734f70f91eff7905a6dda8 fixes the issue
